
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 04:54:18 KST (Jul  7 2026 19:54:18 UTC)

// Verification Directory fv/fdivider 

module fdivider(clk_in, rst_n, o_clk_out);
  input clk_in, rst_n;
  output o_clk_out;
  wire clk_in, rst_n;
  wire o_clk_out;
  wire [3:0] r_count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  DFFRHQX1 \r_count_reg[3] (.RN (rst_n), .CK (clk_in), .D (n_11), .Q
       (r_count[3]));
  SDFFRHQX1 o_clk_out_reg(.RN (rst_n), .CK (clk_in), .D (n_6), .SI
       (o_clk_out), .SE (n_7), .Q (o_clk_out));
  NOR2XL g222__2398(.A (n_5), .B (n_10), .Y (n_11));
  DFFRHQX1 \r_count_reg[1] (.RN (rst_n), .CK (clk_in), .D (n_4), .Q
       (r_count[1]));
  XNOR2X1 g223__5107(.A (r_count[3]), .B (n_8), .Y (n_10));
  AOI21XL g228__6260(.A0 (n_2), .A1 (n_3), .B0 (n_8), .Y (n_9));
  NOR2XL g226__4319(.A (n_6), .B (n_5), .Y (n_7));
  NOR3BXL g227__8428(.AN (n_3), .B (n_1), .C (n_5), .Y (n_4));
  NOR2XL g230__5526(.A (n_2), .B (n_3), .Y (n_8));
  NOR4X1 g231__6783(.A (r_count[0]), .B (r_count[1]), .C (r_count[3]),
       .D (n_2), .Y (n_6));
  NOR4BBX1 g229__3680(.AN (r_count[3]), .BN (r_count[0]), .C
       (r_count[2]), .D (r_count[1]), .Y (n_5));
  NAND2XL g234__1617(.A (r_count[1]), .B (r_count[0]), .Y (n_3));
  NOR2XL g233__2802(.A (r_count[0]), .B (r_count[1]), .Y (n_1));
  DFFRX1 \r_count_reg[2] (.RN (rst_n), .CK (clk_in), .D (n_9), .Q
       (r_count[2]), .QN (n_2));
  DFFRX1 \r_count_reg[0] (.RN (rst_n), .CK (clk_in), .D (n_0), .Q
       (r_count[0]), .QN (n_0));
endmodule

