
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 04:48:51 KST (Jul  7 2026 19:48:51 UTC)

// Verification Directory fv/multiplexed_bus_driver 

module multiplexed_bus_driver(i_data_a, i_data_b, i_en_a, i_en_b,
     o_bus_data);
  input [31:0] i_data_a, i_data_b;
  input i_en_a, i_en_b;
  output [31:0] o_bus_data;
  wire [31:0] i_data_a, i_data_b;
  wire i_en_a, i_en_b;
  wire [31:0] o_bus_data;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_132;
  TBUFXL g22__2398(.A (n_13), .OE (n_132), .Y (o_bus_data[18]));
  TBUFXL g2__5107(.A (n_11), .OE (n_132), .Y (o_bus_data[30]));
  TBUFXL g11__6260(.A (n_5), .OE (n_132), .Y (o_bus_data[29]));
  TBUFXL g12__4319(.A (n_14), .OE (n_132), .Y (o_bus_data[28]));
  TBUFXL g38__8428(.A (n_25), .OE (n_132), .Y (o_bus_data[2]));
  TBUFXL g13__5526(.A (n_4), .OE (n_132), .Y (o_bus_data[27]));
  TBUFXL g14__6783(.A (n_15), .OE (n_132), .Y (o_bus_data[26]));
  TBUFXL g15__3680(.A (n_32), .OE (n_132), .Y (o_bus_data[25]));
  TBUFXL g16__1617(.A (n_1), .OE (n_132), .Y (o_bus_data[24]));
  TBUFXL g17__2802(.A (n_9), .OE (n_132), .Y (o_bus_data[23]));
  TBUFXL g18__1705(.A (n_2), .OE (n_132), .Y (o_bus_data[22]));
  TBUFXL g19__5122(.A (n_23), .OE (n_132), .Y (o_bus_data[21]));
  TBUFXL g30__8246(.A (n_16), .OE (n_132), .Y (o_bus_data[10]));
  TBUFXL g20__7098(.A (n_21), .OE (n_132), .Y (o_bus_data[20]));
  TBUFXL g21__6131(.A (n_30), .OE (n_132), .Y (o_bus_data[19]));
  TBUFXL g10__1881(.A (n_19), .OE (n_132), .Y (o_bus_data[31]));
  TBUFXL g40__5115(.A (n_31), .OE (n_132), .Y (o_bus_data[0]));
  TBUFXL g24__7482(.A (n_22), .OE (n_132), .Y (o_bus_data[16]));
  TBUFXL g25__4733(.A (n_12), .OE (n_132), .Y (o_bus_data[15]));
  TBUFXL g26__6161(.A (n_10), .OE (n_132), .Y (o_bus_data[14]));
  TBUFXL g27__9315(.A (n_6), .OE (n_132), .Y (o_bus_data[13]));
  TBUFXL g28__9945(.A (n_3), .OE (n_132), .Y (o_bus_data[12]));
  TBUFXL g29__2883(.A (n_17), .OE (n_132), .Y (o_bus_data[11]));
  TBUFXL g31__2346(.A (n_18), .OE (n_132), .Y (o_bus_data[9]));
  TBUFXL g32__1666(.A (n_27), .OE (n_132), .Y (o_bus_data[8]));
  TBUFXL g33__7410(.A (n_7), .OE (n_132), .Y (o_bus_data[7]));
  TBUFXL g34__6417(.A (n_26), .OE (n_132), .Y (o_bus_data[6]));
  TBUFXL g35__5477(.A (n_20), .OE (n_132), .Y (o_bus_data[5]));
  TBUFXL g36__2398(.A (n_8), .OE (n_132), .Y (o_bus_data[4]));
  TBUFXL g37__5107(.A (n_29), .OE (n_132), .Y (o_bus_data[3]));
  TBUFXL g39__6260(.A (n_24), .OE (n_132), .Y (o_bus_data[1]));
  TBUFXL g23__4319(.A (n_28), .OE (n_132), .Y (o_bus_data[17]));
  MX2X1 g885__5526(.A (i_data_b[25]), .B (i_data_a[25]), .S0 (i_en_a),
       .Y (n_32));
  MX2X1 g881__6783(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (i_en_a), .Y
       (n_31));
  MX2X1 g882__3680(.A (i_data_b[19]), .B (i_data_a[19]), .S0 (i_en_a),
       .Y (n_30));
  MX2X1 g888__1617(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (i_en_a), .Y
       (n_29));
  MX2X1 g889__2802(.A (i_data_b[17]), .B (i_data_a[17]), .S0 (i_en_a),
       .Y (n_28));
  MX2X1 g877__1705(.A (i_data_b[8]), .B (i_data_a[8]), .S0 (i_en_a), .Y
       (n_27));
  MX2X1 g883__5122(.A (i_data_b[6]), .B (i_data_a[6]), .S0 (i_en_a), .Y
       (n_26));
  MX2X1 g890__8246(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (i_en_a), .Y
       (n_25));
  MX2X1 g891__7098(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_en_a), .Y
       (n_24));
  MX2X1 g873__6131(.A (i_data_b[21]), .B (i_data_a[21]), .S0 (i_en_a),
       .Y (n_23));
  MX2X1 g893__1881(.A (i_data_b[16]), .B (i_data_a[16]), .S0 (i_en_a),
       .Y (n_22));
  MX2X1 g878__5115(.A (i_data_b[20]), .B (i_data_a[20]), .S0 (i_en_a),
       .Y (n_21));
  MX2X1 g884__7482(.A (i_data_b[5]), .B (i_data_a[5]), .S0 (i_en_a), .Y
       (n_20));
  MX2X1 g892__4733(.A (i_data_b[31]), .B (i_data_a[31]), .S0 (i_en_a),
       .Y (n_19));
  MX2X1 g875__6161(.A (i_data_b[9]), .B (i_data_a[9]), .S0 (i_en_a), .Y
       (n_18));
  MX2X1 g904__9315(.A (i_data_b[11]), .B (i_data_a[11]), .S0 (i_en_a),
       .Y (n_17));
  MX2X1 g874__9945(.A (i_data_b[10]), .B (i_data_a[10]), .S0 (i_en_a),
       .Y (n_16));
  MX2X1 g879__2883(.A (i_data_b[26]), .B (i_data_a[26]), .S0 (i_en_a),
       .Y (n_15));
  MX2X1 g895__2346(.A (i_data_b[28]), .B (i_data_a[28]), .S0 (i_en_a),
       .Y (n_14));
  MX2X1 g886__1666(.A (i_data_b[18]), .B (i_data_a[18]), .S0 (i_en_a),
       .Y (n_13));
  MX2X1 g896__7410(.A (i_data_b[15]), .B (i_data_a[15]), .S0 (i_en_a),
       .Y (n_12));
  MX2X1 g897__6417(.A (i_data_b[30]), .B (i_data_a[30]), .S0 (i_en_a),
       .Y (n_11));
  MX2X1 g898__5477(.A (i_data_b[14]), .B (i_data_a[14]), .S0 (i_en_a),
       .Y (n_10));
  MX2X1 g899__2398(.A (i_data_b[23]), .B (i_data_a[23]), .S0 (i_en_a),
       .Y (n_9));
  MX2X1 g872__5107(.A (i_data_b[4]), .B (i_data_a[4]), .S0 (i_en_a), .Y
       (n_8));
  MX2X1 g880__6260(.A (i_data_b[7]), .B (i_data_a[7]), .S0 (i_en_a), .Y
       (n_7));
  MX2X1 g900__4319(.A (i_data_b[13]), .B (i_data_a[13]), .S0 (i_en_a),
       .Y (n_6));
  MX2X1 g876__8428(.A (i_data_b[29]), .B (i_data_a[29]), .S0 (i_en_a),
       .Y (n_5));
  MX2X1 g901__5526(.A (i_data_b[27]), .B (i_data_a[27]), .S0 (i_en_a),
       .Y (n_4));
  MX2X1 g902__6783(.A (i_data_b[12]), .B (i_data_a[12]), .S0 (i_en_a),
       .Y (n_3));
  MX2X1 g903__3680(.A (i_data_b[22]), .B (i_data_a[22]), .S0 (i_en_a),
       .Y (n_2));
  MX2X1 g894__1617(.A (i_data_b[24]), .B (i_data_a[24]), .S0 (i_en_a),
       .Y (n_1));
  XOR2X2 g2(.A (i_en_a), .B (i_en_b), .Y (n_132));
endmodule

