
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 04:58:40 KST (Jul  7 2026 19:58:40 UTC)

// Verification Directory fv/simple_register 

module simple_register(clk, rst_n, wen, i_wdata, o_rdata);
  input clk, rst_n, wen;
  input [31:0] i_wdata;
  output [31:0] o_rdata;
  wire clk, rst_n, wen;
  wire [31:0] i_wdata;
  wire [31:0] o_rdata;
  SDFFRHQX1 \r_reg32_reg[20] (.RN (rst_n), .CK (clk), .D (o_rdata[20]),
       .SI (i_wdata[20]), .SE (wen), .Q (o_rdata[20]));
  SDFFRHQX1 \r_reg32_reg[10] (.RN (rst_n), .CK (clk), .D (o_rdata[10]),
       .SI (i_wdata[10]), .SE (wen), .Q (o_rdata[10]));
  SDFFRHQX1 \r_reg32_reg[11] (.RN (rst_n), .CK (clk), .D (o_rdata[11]),
       .SI (i_wdata[11]), .SE (wen), .Q (o_rdata[11]));
  SDFFRHQX1 \r_reg32_reg[12] (.RN (rst_n), .CK (clk), .D (o_rdata[12]),
       .SI (i_wdata[12]), .SE (wen), .Q (o_rdata[12]));
  SDFFRHQX1 \r_reg32_reg[4] (.RN (rst_n), .CK (clk), .D (o_rdata[4]),
       .SI (i_wdata[4]), .SE (wen), .Q (o_rdata[4]));
  SDFFRHQX1 \r_reg32_reg[1] (.RN (rst_n), .CK (clk), .D (o_rdata[1]),
       .SI (i_wdata[1]), .SE (wen), .Q (o_rdata[1]));
  SDFFRHQX1 \r_reg32_reg[9] (.RN (rst_n), .CK (clk), .D (o_rdata[9]),
       .SI (i_wdata[9]), .SE (wen), .Q (o_rdata[9]));
  SDFFRHQX1 \r_reg32_reg[14] (.RN (rst_n), .CK (clk), .D (o_rdata[14]),
       .SI (i_wdata[14]), .SE (wen), .Q (o_rdata[14]));
  SDFFRHQX1 \r_reg32_reg[15] (.RN (rst_n), .CK (clk), .D (o_rdata[15]),
       .SI (i_wdata[15]), .SE (wen), .Q (o_rdata[15]));
  SDFFRHQX1 \r_reg32_reg[16] (.RN (rst_n), .CK (clk), .D (o_rdata[16]),
       .SI (i_wdata[16]), .SE (wen), .Q (o_rdata[16]));
  SDFFRHQX1 \r_reg32_reg[7] (.RN (rst_n), .CK (clk), .D (o_rdata[7]),
       .SI (i_wdata[7]), .SE (wen), .Q (o_rdata[7]));
  SDFFRHQX1 \r_reg32_reg[17] (.RN (rst_n), .CK (clk), .D (o_rdata[17]),
       .SI (i_wdata[17]), .SE (wen), .Q (o_rdata[17]));
  SDFFRHQX1 \r_reg32_reg[18] (.RN (rst_n), .CK (clk), .D (o_rdata[18]),
       .SI (i_wdata[18]), .SE (wen), .Q (o_rdata[18]));
  SDFFRHQX1 \r_reg32_reg[19] (.RN (rst_n), .CK (clk), .D (o_rdata[19]),
       .SI (i_wdata[19]), .SE (wen), .Q (o_rdata[19]));
  SDFFRHQX1 \r_reg32_reg[5] (.RN (rst_n), .CK (clk), .D (o_rdata[5]),
       .SI (i_wdata[5]), .SE (wen), .Q (o_rdata[5]));
  SDFFRHQX1 \r_reg32_reg[25] (.RN (rst_n), .CK (clk), .D (o_rdata[25]),
       .SI (i_wdata[25]), .SE (wen), .Q (o_rdata[25]));
  SDFFRHQX1 \r_reg32_reg[8] (.RN (rst_n), .CK (clk), .D (o_rdata[8]),
       .SI (i_wdata[8]), .SE (wen), .Q (o_rdata[8]));
  SDFFRHQX1 \r_reg32_reg[2] (.RN (rst_n), .CK (clk), .D (o_rdata[2]),
       .SI (i_wdata[2]), .SE (wen), .Q (o_rdata[2]));
  SDFFRHQX1 \r_reg32_reg[3] (.RN (rst_n), .CK (clk), .D (o_rdata[3]),
       .SI (i_wdata[3]), .SE (wen), .Q (o_rdata[3]));
  SDFFRHQX1 \r_reg32_reg[22] (.RN (rst_n), .CK (clk), .D (o_rdata[22]),
       .SI (i_wdata[22]), .SE (wen), .Q (o_rdata[22]));
  SDFFRHQX1 \r_reg32_reg[23] (.RN (rst_n), .CK (clk), .D (o_rdata[23]),
       .SI (i_wdata[23]), .SE (wen), .Q (o_rdata[23]));
  SDFFRHQX1 \r_reg32_reg[24] (.RN (rst_n), .CK (clk), .D (o_rdata[24]),
       .SI (i_wdata[24]), .SE (wen), .Q (o_rdata[24]));
  SDFFRHQX1 \r_reg32_reg[0] (.RN (rst_n), .CK (clk), .D (o_rdata[0]),
       .SI (i_wdata[0]), .SE (wen), .Q (o_rdata[0]));
  SDFFRHQX1 \r_reg32_reg[13] (.RN (rst_n), .CK (clk), .D (o_rdata[13]),
       .SI (i_wdata[13]), .SE (wen), .Q (o_rdata[13]));
  SDFFRHQX1 \r_reg32_reg[26] (.RN (rst_n), .CK (clk), .D (o_rdata[26]),
       .SI (i_wdata[26]), .SE (wen), .Q (o_rdata[26]));
  SDFFRHQX1 \r_reg32_reg[27] (.RN (rst_n), .CK (clk), .D (o_rdata[27]),
       .SI (i_wdata[27]), .SE (wen), .Q (o_rdata[27]));
  SDFFRHQX1 \r_reg32_reg[28] (.RN (rst_n), .CK (clk), .D (o_rdata[28]),
       .SI (i_wdata[28]), .SE (wen), .Q (o_rdata[28]));
  SDFFRHQX1 \r_reg32_reg[29] (.RN (rst_n), .CK (clk), .D (o_rdata[29]),
       .SI (i_wdata[29]), .SE (wen), .Q (o_rdata[29]));
  SDFFRHQX1 \r_reg32_reg[6] (.RN (rst_n), .CK (clk), .D (o_rdata[6]),
       .SI (i_wdata[6]), .SE (wen), .Q (o_rdata[6]));
  SDFFRHQX1 \r_reg32_reg[30] (.RN (rst_n), .CK (clk), .D (o_rdata[30]),
       .SI (i_wdata[30]), .SE (wen), .Q (o_rdata[30]));
  SDFFRHQX1 \r_reg32_reg[31] (.RN (rst_n), .CK (clk), .D (o_rdata[31]),
       .SI (i_wdata[31]), .SE (wen), .Q (o_rdata[31]));
  SDFFRHQX1 \r_reg32_reg[21] (.RN (rst_n), .CK (clk), .D (o_rdata[21]),
       .SI (i_wdata[21]), .SE (wen), .Q (o_rdata[21]));
endmodule

