
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 04:57:11 KST (Jul  7 2026 19:57:11 UTC)

// Verification Directory fv/shift_register_sipo 

module shift_register_sipo(clk, rst_n, i_serial_in, o_parallel_out);
  input clk, rst_n, i_serial_in;
  output [8:0] o_parallel_out;
  wire clk, rst_n, i_serial_in;
  wire [8:0] o_parallel_out;
  assign o_parallel_out[8] = 1'b0;
  DFFRHQX1 \r_shift_reg[7] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[6]), .Q (o_parallel_out[7]));
  DFFRHQX1 \r_shift_reg[6] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[5]), .Q (o_parallel_out[6]));
  DFFRHQX1 \r_shift_reg[5] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[4]), .Q (o_parallel_out[5]));
  DFFRHQX1 \r_shift_reg[4] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[3]), .Q (o_parallel_out[4]));
  DFFRHQX1 \r_shift_reg[3] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[2]), .Q (o_parallel_out[3]));
  DFFRHQX1 \r_shift_reg[2] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[1]), .Q (o_parallel_out[2]));
  DFFRHQX1 \r_shift_reg[1] (.RN (rst_n), .CK (clk), .D
       (o_parallel_out[0]), .Q (o_parallel_out[1]));
  DFFRHQX1 \r_shift_reg[0] (.RN (rst_n), .CK (clk), .D (i_serial_in),
       .Q (o_parallel_out[0]));
endmodule

