
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 04:06:26 KST (Jul  7 2026 19:06:26 UTC)

// Verification Directory fv/register 

module register(rst_n, clk, i_in1, i_in2, o_out1, o_out2);
  input rst_n, clk, i_in1;
  input [3:0] i_in2;
  output o_out1;
  output [3:0] o_out2;
  wire rst_n, clk, i_in1;
  wire [3:0] i_in2;
  wire o_out1;
  wire [3:0] o_out2;
  DFFRHQX1 o_out1_reg(.RN (rst_n), .CK (clk), .D (i_in1), .Q (o_out1));
  DFFRHQX1 \o_out2_reg[3] (.RN (rst_n), .CK (clk), .D (i_in2[3]), .Q
       (o_out2[3]));
  DFFRHQX1 \o_out2_reg[1] (.RN (rst_n), .CK (clk), .D (i_in2[1]), .Q
       (o_out2[1]));
  DFFRHQX1 \o_out2_reg[0] (.RN (rst_n), .CK (clk), .D (i_in2[0]), .Q
       (o_out2[0]));
  DFFRHQX1 \o_out2_reg[2] (.RN (rst_n), .CK (clk), .D (i_in2[2]), .Q
       (o_out2[2]));
endmodule

