
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 02:35:02 KST (Jul  7 2026 17:35:02 UTC)

// Verification Directory fv/gpio_mux 

module gpio_mux(i_sel, i_tx0, i_rx0, i_pwm1, i_other_signal,
     o_gpio_pin);
  input [1:0] i_sel;
  input i_tx0, i_rx0, i_pwm1, i_other_signal;
  output o_gpio_pin;
  wire [1:0] i_sel;
  wire i_tx0, i_rx0, i_pwm1, i_other_signal;
  wire o_gpio_pin;
  MX4XL g90__2398(.A (i_tx0), .B (i_other_signal), .C (i_rx0), .D
       (i_pwm1), .S0 (i_sel[1]), .S1 (i_sel[0]), .Y (o_gpio_pin));
endmodule

