
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:30:27 KST (Jul  7 2026 18:30:27 UTC)

// Verification Directory fv/interrupt_controller 

module interrupt_controller(i_int, i_int_ack, o_int_id, o_int_req);
  input [7:0] i_int;
  input i_int_ack;
  output [2:0] o_int_id;
  output o_int_req;
  wire [7:0] i_int;
  wire i_int_ack;
  wire [2:0] o_int_id;
  wire o_int_req;
  wire n_0, n_1, n_2, n_4, n_6, n_7, n_10, n_22;
  AOI2BB1XL g308__2398(.A0N (i_int[7]), .A1N (n_10), .B0 (i_int_ack),
       .Y (o_int_id[0]));
  NOR2XL g309__5107(.A (i_int_ack), .B (n_22), .Y (o_int_req));
  AOI2BB1XL g311__6260(.A0N (i_int[5]), .A1N (n_6), .B0 (i_int[6]), .Y
       (n_10));
  NOR2BX1 g310__4319(.AN (n_7), .B (i_int_ack), .Y (o_int_id[1]));
  OAI31X1 g314__5526(.A0 (i_int[5]), .A1 (i_int[4]), .A2 (n_2), .B0
       (n_0), .Y (n_7));
  AOI2BB1XL g315__6783(.A0N (i_int[3]), .A1N (n_1), .B0 (i_int[4]), .Y
       (n_6));
  NOR2BX1 g313__3680(.AN (n_4), .B (i_int_ack), .Y (o_int_id[2]));
  OR4X1 g316__1617(.A (i_int[6]), .B (i_int[7]), .C (i_int[4]), .D
       (i_int[5]), .Y (n_4));
  NOR2XL g318__2802(.A (i_int[2]), .B (i_int[3]), .Y (n_2));
  NOR2BX1 g319__1705(.AN (i_int[1]), .B (i_int[2]), .Y (n_1));
  NOR2XL g320__5122(.A (i_int[6]), .B (i_int[7]), .Y (n_0));
  NOR4BX1 g2(.AN (n_2), .B (i_int[0]), .C (i_int[1]), .D (n_4), .Y
       (n_22));
endmodule

