
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 04:51:30 KST (Jul  7 2026 19:51:30 UTC)

// Verification Directory fv/bidirectional_bus_driver 

module bidirectional_bus_driver(i_data_to_bus, i_send, i_rcv,
     io_bus_data, o_data_from_bus);
  input [31:0] i_data_to_bus;
  input i_send, i_rcv;
  output [31:0] o_data_from_bus;
  inout [31:0] io_bus_data;
  wire [31:0] i_data_to_bus;
  wire i_send, i_rcv;
  wire [31:0] o_data_from_bus;
  wire [31:0] io_bus_data;
  AND2XL g273__2398(.A (i_rcv), .B (io_bus_data[19]), .Y
       (o_data_from_bus[19]));
  AND2XL g266__5107(.A (i_rcv), .B (io_bus_data[30]), .Y
       (o_data_from_bus[30]));
  AND2XL g287__6260(.A (i_rcv), .B (io_bus_data[29]), .Y
       (o_data_from_bus[29]));
  AND2XL g277__4319(.A (i_rcv), .B (io_bus_data[28]), .Y
       (o_data_from_bus[28]));
  AND2XL g288__8428(.A (i_rcv), .B (io_bus_data[27]), .Y
       (o_data_from_bus[27]));
  AND2XL g296__5526(.A (i_rcv), .B (io_bus_data[3]), .Y
       (o_data_from_bus[3]));
  AND2XL g267__6783(.A (i_rcv), .B (io_bus_data[26]), .Y
       (o_data_from_bus[26]));
  AND2XL g272__3680(.A (i_rcv), .B (io_bus_data[25]), .Y
       (o_data_from_bus[25]));
  AND2XL g282__1617(.A (i_rcv), .B (io_bus_data[24]), .Y
       (o_data_from_bus[24]));
  AND2XL g274__2802(.A (i_rcv), .B (io_bus_data[7]), .Y
       (o_data_from_bus[7]));
  AND2XL g289__1705(.A (i_rcv), .B (io_bus_data[23]), .Y
       (o_data_from_bus[23]));
  AND2XL g293__5122(.A (i_rcv), .B (io_bus_data[22]), .Y
       (o_data_from_bus[22]));
  AND2XL g295__8246(.A (i_rcv), .B (io_bus_data[21]), .Y
       (o_data_from_bus[21]));
  AND2XL g281__7098(.A (i_rcv), .B (io_bus_data[11]), .Y
       (o_data_from_bus[11]));
  AND2XL g268__6131(.A (i_rcv), .B (io_bus_data[20]), .Y
       (o_data_from_bus[20]));
  AND2XL g280__1881(.A (i_rcv), .B (io_bus_data[31]), .Y
       (o_data_from_bus[31]));
  AND2XL g286__5115(.A (i_rcv), .B (io_bus_data[0]), .Y
       (o_data_from_bus[0]));
  AND2XL g265__7482(.A (i_rcv), .B (io_bus_data[17]), .Y
       (o_data_from_bus[17]));
  AND2XL g285__4733(.A (i_rcv), .B (io_bus_data[16]), .Y
       (o_data_from_bus[16]));
  AND2XL g290__6161(.A (i_rcv), .B (io_bus_data[15]), .Y
       (o_data_from_bus[15]));
  AND2XL g291__9315(.A (i_rcv), .B (io_bus_data[14]), .Y
       (o_data_from_bus[14]));
  AND2XL g292__9945(.A (i_rcv), .B (io_bus_data[13]), .Y
       (o_data_from_bus[13]));
  AND2XL g294__2883(.A (i_rcv), .B (io_bus_data[12]), .Y
       (o_data_from_bus[12]));
  AND2XL g269__2346(.A (i_rcv), .B (io_bus_data[10]), .Y
       (o_data_from_bus[10]));
  AND2XL g270__1666(.A (i_rcv), .B (io_bus_data[9]), .Y
       (o_data_from_bus[9]));
  AND2XL g271__7410(.A (i_rcv), .B (io_bus_data[8]), .Y
       (o_data_from_bus[8]));
  AND2XL g275__6417(.A (i_rcv), .B (io_bus_data[6]), .Y
       (o_data_from_bus[6]));
  AND2XL g276__5477(.A (i_rcv), .B (io_bus_data[5]), .Y
       (o_data_from_bus[5]));
  AND2XL g279__2398(.A (i_rcv), .B (io_bus_data[4]), .Y
       (o_data_from_bus[4]));
  AND2XL g283__5107(.A (i_rcv), .B (io_bus_data[2]), .Y
       (o_data_from_bus[2]));
  AND2XL g284__6260(.A (i_rcv), .B (io_bus_data[1]), .Y
       (o_data_from_bus[1]));
  AND2XL g278__4319(.A (i_rcv), .B (io_bus_data[18]), .Y
       (o_data_from_bus[18]));
  TBUFX1 g18__8428(.A (i_data_to_bus[17]), .OE (i_send), .Y
       (io_bus_data[17]));
  TBUFX1 g29__5526(.A (i_data_to_bus[6]), .OE (i_send), .Y
       (io_bus_data[6]));
  TBUFX1 g19__6783(.A (i_data_to_bus[16]), .OE (i_send), .Y
       (io_bus_data[16]));
  TBUFX1 g14__3680(.A (i_data_to_bus[21]), .OE (i_send), .Y
       (io_bus_data[21]));
  TBUFX1 g35__1617(.A (i_data_to_bus[0]), .OE (i_send), .Y
       (io_bus_data[0]));
  TBUFX1 g7__2802(.A (i_data_to_bus[28]), .OE (i_send), .Y
       (io_bus_data[28]));
  TBUFX1 g11__1705(.A (i_data_to_bus[24]), .OE (i_send), .Y
       (io_bus_data[24]));
  TBUFX1 g15__5122(.A (i_data_to_bus[20]), .OE (i_send), .Y
       (io_bus_data[20]));
  TBUFX1 g16__8246(.A (i_data_to_bus[19]), .OE (i_send), .Y
       (io_bus_data[19]));
  TBUFX1 g30__7098(.A (i_data_to_bus[5]), .OE (i_send), .Y
       (io_bus_data[5]));
  TBUFX1 g20__6131(.A (i_data_to_bus[15]), .OE (i_send), .Y
       (io_bus_data[15]));
  TBUFX1 g5__1881(.A (i_data_to_bus[30]), .OE (i_send), .Y
       (io_bus_data[30]));
  TBUFX1 g25__5115(.A (i_data_to_bus[10]), .OE (i_send), .Y
       (io_bus_data[10]));
  TBUFX1 g17__7482(.A (i_data_to_bus[18]), .OE (i_send), .Y
       (io_bus_data[18]));
  TBUFX1 g21__4733(.A (i_data_to_bus[14]), .OE (i_send), .Y
       (io_bus_data[14]));
  TBUFX1 g9__6161(.A (i_data_to_bus[26]), .OE (i_send), .Y
       (io_bus_data[26]));
  TBUFX1 g12__9315(.A (i_data_to_bus[23]), .OE (i_send), .Y
       (io_bus_data[23]));
  TBUFX1 g31__9945(.A (i_data_to_bus[4]), .OE (i_send), .Y
       (io_bus_data[4]));
  TBUFX1 g22__2883(.A (i_data_to_bus[13]), .OE (i_send), .Y
       (io_bus_data[13]));
  TBUFX1 g23__2346(.A (i_data_to_bus[12]), .OE (i_send), .Y
       (io_bus_data[12]));
  TBUFX1 g10__1666(.A (i_data_to_bus[25]), .OE (i_send), .Y
       (io_bus_data[25]));
  TBUFX1 g26__7410(.A (i_data_to_bus[9]), .OE (i_send), .Y
       (io_bus_data[9]));
  TBUFX1 g13__6417(.A (i_data_to_bus[22]), .OE (i_send), .Y
       (io_bus_data[22]));
  TBUFX1 g8__5477(.A (i_data_to_bus[27]), .OE (i_send), .Y
       (io_bus_data[27]));
  TBUFX1 g28__2398(.A (i_data_to_bus[7]), .OE (i_send), .Y
       (io_bus_data[7]));
  TBUFX1 g1__5107(.A (i_data_to_bus[31]), .OE (i_send), .Y
       (io_bus_data[31]));
  TBUFX1 g24__6260(.A (i_data_to_bus[11]), .OE (i_send), .Y
       (io_bus_data[11]));
  TBUFX1 g34__4319(.A (i_data_to_bus[1]), .OE (i_send), .Y
       (io_bus_data[1]));
  TBUFX1 g32__8428(.A (i_data_to_bus[3]), .OE (i_send), .Y
       (io_bus_data[3]));
  TBUFX1 g6__5526(.A (i_data_to_bus[29]), .OE (i_send), .Y
       (io_bus_data[29]));
  TBUFX1 g33__6783(.A (i_data_to_bus[2]), .OE (i_send), .Y
       (io_bus_data[2]));
  TBUFX1 g27__3680(.A (i_data_to_bus[8]), .OE (i_send), .Y
       (io_bus_data[8]));
endmodule

