
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:48:09 KST (Jul  7 2026 18:48:09 UTC)

// Verification Directory fv/bcd_to_7seg 

module bcd_to_7seg(i_bcd, o_seg);
  input [3:0] i_bcd;
  output [6:0] o_seg;
  wire [3:0] i_bcd;
  wire [6:0] o_seg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_11, n_12, n_13, n_14, n_16, n_19;
  NOR2BX1 g372__2398(.AN (n_16), .B (n_19), .Y (o_seg[3]));
  NOR2XL g373__5107(.A (n_13), .B (n_19), .Y (o_seg[1]));
  AOI21XL g374__6260(.A0 (n_9), .A1 (n_6), .B0 (n_19), .Y (o_seg[0]));
  AND2XL g375__4319(.A (n_16), .B (n_14), .Y (o_seg[6]));
  OAI211X1 g376__8428(.A0 (i_bcd[2]), .A1 (n_5), .B0 (n_11), .C0 (n_3),
       .Y (o_seg[2]));
  OAI21XL g377__5526(.A0 (n_12), .A1 (n_4), .B0 (n_14), .Y (n_19));
  NAND2XL g379__6783(.A (n_12), .B (n_11), .Y (n_13));
  OA21X1 g380__3680(.A0 (n_9), .A1 (n_0), .B0 (n_7), .Y (o_seg[5]));
  AND2XL g378__1617(.A (n_7), .B (n_11), .Y (o_seg[4]));
  AOI31X1 g381__2802(.A0 (i_bcd[0]), .A1 (n_2), .A2 (n_6), .B0 (n_1),
       .Y (n_14));
  OR2X1 g384__1705(.A (n_5), .B (n_4), .Y (n_16));
  OR3X1 g382__5122(.A (i_bcd[0]), .B (n_2), .C (n_4), .Y (n_3));
  NAND3BXL g383__8246(.AN (i_bcd[0]), .B (i_bcd[1]), .C (n_6), .Y
       (n_11));
  INVXL g385(.A (n_7), .Y (n_1));
  NAND2BXL g386__7098(.AN (n_4), .B (n_12), .Y (n_0));
  INVXL g388(.A (n_9), .Y (n_5));
  OAI21XL g387__6131(.A0 (i_bcd[1]), .A1 (i_bcd[2]), .B0 (i_bcd[3]), .Y
       (n_7));
  NOR2XL g391__1881(.A (i_bcd[2]), .B (i_bcd[3]), .Y (n_6));
  NAND2BXL g392__5115(.AN (i_bcd[3]), .B (i_bcd[2]), .Y (n_4));
  NAND2XL g389__7482(.A (i_bcd[0]), .B (i_bcd[1]), .Y (n_12));
  NOR2XL g390__4733(.A (i_bcd[0]), .B (i_bcd[1]), .Y (n_9));
  INVXL g393(.A (i_bcd[1]), .Y (n_2));
endmodule

